Min cal 만들었어요 확인좀요
JiwonDev/java-study pull request #24
Opened 2022-04-27 15:22 UTC by Eco-Min

2022-04-27 16:18 UTC, JiwonDev requested changes
코드가 깔끔해서 좋네요👏
다만 의미 있는 단위로 줄바꿈을 섞어주시면, 코드를 읽기가 더 편해질 것 같아요.

`null을 반환하는 부분`만 수정해주시면, 나머지는 지금 당장 수정할 필요는 없을 듯 해요.
이 부분만 고치면 바로 머지 승인하도록 할게요😄

2022-04-27 16:18 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +                        throw new RuntimeException("0으로 나누기 불가");
`0으로 나누었을 때`를 Checked 예외가 아닌 런타임 예외로 사용하신 이유가 있으실까요?😄

2022-04-27 16:18 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +        this.operatorMap = Map.of(
`operatorMap`을 생성하는 부분을 다른 클래스로 분리하는 건 어떨까요? 생성자에 있는 건 조금 어색하긴 하네요.

의견이 궁금합니다.🤔

2022-04-27 16:18 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +    public Double start(String fun) {
`start` 메서드가 반환값이 있는게 어색 해보여요. 시작 한 다음 무엇을 반환하는지도 모호하구요.

`calculate` 나 `execute` 같은 이름은 어떨까요?

2022-04-27 16:18 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +        PreParedCalculator preParedCalculator = new PreParedCalculator();
`start`라는 메서드가 내부에서 `new`로 객체를 생성한다고 예측하기 어려울 것 같아요.
`PreParedCalculator`를 매번 생성해주어야 할까요?

2022-04-27 16:18 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +        boolean correctExpression = preParedCalculator.isCorrectExpression(fun);
`correctExpression` 은 무슨 조건인지 한눈에 안보이는 것 같아요.
`isValid`나 `isCorrect` 정도로 줄여 쓰더라도, 파라메타 타입을 보고 유추할 수 있지 않을까요?

2022-04-27 16:18 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +        return 0D;
`0D`를 왜 반환하는지 알기 어려운 것 같아요.
필드나 메서드로 추상화를 하는게 어떨까요? `return DEFAULT_VALUE` 이런 느낌으로요.

2022-04-27 16:18 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +        return numbers.stream().reduce((x, y) ->
스트림을 사용하여 코드가 깔끔하긴 하지만, 가독성은 조금 떨어지는 듯해요.
일부를 변수로 뽑아서 가독성을 늘리는 건 어떨까요?

2022-04-27 16:18 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/PreParedCalculator.java
> +        return null;
`null`을 반환해버리면 나중에 버그가 발생했을 때 디버깅이 어려워 질 것 같아요.
빈 리스트를 반환하는 건 어떨까요?

2022-04-27 16:18 UTC, JiwonDev commented on src/test/java/com/_min_StringCalculator/domain/CalculatorTest.java
> +        //act
`Arrange-Act-Assert`로 나누는 건 좋지만, 사용하지 않는 부분을 공백으로 띄워두는 건 가독성이 별로인 것 같아요. 
어떻게 생각하시나요?

2022-04-29 08:27 UTC, Eco-Min commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +    public Double start(String fun) {
네이밍 바꿀필요성은 있습니다.반영해보도록 하겠습니다

2022-04-29 08:30 UTC, Eco-Min commented on src/main/java/com/_min_StringCalculator/domain/PreParedCalculator.java
> +        return null;
맞습니다 빈리스트가더 좋죠 이부분을 좀더신경써야겠네요

2022-04-29 08:31 UTC, Eco-Min commented on src/test/java/com/_min_StringCalculator/domain/CalculatorTest.java
> +        //act
Given when then 에서 이번에 바꿔 처리해봤습니다
아직 익숙하지않아그래요..

2022-04-29 12:43 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +        PreParedCalculator preParedCalculator = new PreParedCalculator();
당장은 무엇을 선택해도 상관없지만, 서비스 객체를 `new`로 매번 생성하는 건 선호하지 않는 방법이긴 합니다.
- `start()` 같은 서비스 메서드는 상당히 자주 호출될 텐데, 매번 객체를 생성하고 GC하는 비용이 커집니다.
- 보통 서비스 객체는 인스턴스마다 고유의 상태 값을 가질 필요가 없습니다.
- 객체간의 의존성이 복잡해집니다. 테스트하기 어려워지고, OCP 를 지키기 어려워집니다.

물론 `DTO` 같이 값만 전달하는 객체라면 매번 `new`로 만들어도 큰 문제가 되지 않겠지만, 
서비스 객체는 다른 객체와 의존성이 엮어있고, 동작이 자주 바뀔 수 있기에 조금 더 생각해볼 필요가 있을 듯 합니다.

2022-05-01 14:07 UTC, Eco-Min commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +        PreParedCalculator preParedCalculator = new PreParedCalculator();
아 저부분을 서비스 객체로 뽑는게 아니라 저부분을 서비스 객체에서 di 로 받게 만드는게 최선의 방법이겠지요

2022-05-01 14:08 UTC, Eco-Min commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +        return 0D;
그부분이 조금더 좋긴 합니다 지금 당장 확장성을 생각하지 않고 만든게 큽니다. 깊이 생각하지 못한부분이였네요

2022-05-01 14:09 UTC, Eco-Min commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +        return numbers.stream().reduce((x, y) ->
() -> { } 로 변환하여 조금더 직관적이게 해도 될듯합니다

2022-05-02 12:42 UTC, JiwonDev commented on src/main/java/com/_min_StringCalculator/domain/Calculator.java
> +                        throw new RuntimeException("0으로 나누기 불가");
Checked Exception과 Runtime Exception의 차이에 대해서 알아보시면 좋을 것 같아요.

그리고 스프링 트랜잭션에서, 어떠한 예외가 발생하면 롤백이 되고 왜 그런지도 공부하시면 더 좋을 거 같습니다!

2022-05-02 13:41 UTC, JiwonDev approved these changes

2022-05-02 14:16 UTC, closed without merging