문자열 계산기 사칙연산
JiwonDev/java-study pull request #25
Opened 2022-04-29 07:48 UTC by somyiha

확인좀요

2022-04-29 08:22 UTC, JiwonDev requested changes
깃허브에 익숙하지 않으신 걸로 아는데, PR 잘 날려주셨네요. 좋습니다 😀
다른 부분은 괜찮은데, 주석이 너무 많은 것 같아요. 

의미 없는 주석만 삭제해주시면 병합해도 괜찮을 듯 합니다.

참고로 코드로 여러가지 실험을 하고 있어서 그랬다면 
- `Git Branch` 로 작업 폴더를 구분하거나 
- `Git Stash` 로 현재 작업중인 내용을 임시저장하는 기능을 활용하는 것도 괜찮아보여요.

2022-04-29 08:22 UTC, JiwonDev commented on src/main/java/com/samsung/StringCal.java
> +        return result;
public 메서드를 읽기 보기 쉽도록 깔끔하게 작성해주셨네요.  최고에요👍

다만 `arithmetic`은 명사라서 메서드 이름으로는 어울리지 않는 거 같아요.
`doArithmetic()` 또는 연산을 하는 메서드니까 `calculate()` `apply()` 같은 네이밍은 어떨까요?

2022-04-29 08:22 UTC, JiwonDev commented on src/main/java/com/samsung/StringCal.java
> +            if (exceptionCnt > 1) { // operator 연속
```java
if(...) // operator 연속일 때
```

이러한 형태의 주석은 처음에는 괜찮지만, 프로젝트가 커지면서 문제가 많이 생길 것 같아요.
- 프로젝트가 커지며, 코드가 추가된다면 주석을 알아보기 힘들어지고
- 주석에 적힌 동작을 개발자마다 조금씩 다르게 해석할 수 있으며
- 남이 적은 주석이라 함부로 지울 수 없어서, 코드 가독성이 더러워 질 것 같아요.

주석이 아닌 코드만으로 충분히 의미를 나타낼 수 있지 않을까요? 예를 들어 아래와 같이 메서드로 뽑아내는거죠.
```java
boolean isOk(int exceptionCnt){  /* isOk() 는 예시입니다. 더 이해하기 쉬운 이름을 생각해보죠! */
    return exceptionCnt > 1
}
```

2022-04-29 08:22 UTC, JiwonDev commented on src/main/java/com/samsung/StringCal.java
> +                formula.add((splitArr[i]));
이 부분은 어떠한 예외를 처리하기 위한 코드인지 여쭤봐도 될까요?🤔

2022-04-29 08:22 UTC, JiwonDev commented on src/main/java/com/samsung/StringCal.java
> +    public List<String> makeFormula (String[] splitArr) {
`makeFormula`는 다른 곳에서 재사용 할 계획이 있으신가요?

`public` 메서드로 지정한 이유가 궁금합니다.😀

2022-04-29 08:49 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
>  public final class StringCal {
상속할일이 없을것같고 써보고싶어서 한번 써봤습니다~~~

2022-04-29 08:49 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +    public String[] split (String str) {
이것저것 시도했던 흔적이요 😅

2022-04-29 08:56 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +    public int calculate (String strFormula) {
`arithmetic()`에서 받는 인자가 진짜 계산식라고 생각이들어서  `formula` 라고 지었고
`strFormula`는 계산식을 만들기 전의 단순한 String이라서 `strFormula` 라고 지었어요!

2022-04-29 08:58 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +        return result;
`calculate()`는 이미 있어서 `doArithmetic()` 좋을것같아요!

2022-04-29 09:00 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +            if (exceptionCnt > 1) { // operator 연속
아하 주석도 문제가 될 수 있네요! 새로 알아갑니당

2022-04-29 09:05 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +                formula.add((splitArr[i]));
try에서는 숫자를, catch에서는 연산자를 `formula` list에 추가하는 코드입니다 🙄

2022-04-29 09:07 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +    public List<String> makeFormula (String[] splitArr) {
습관처럼 썼어요 😅

2022-04-29 13:00 UTC, JiwonDev commented on src/main/java/com/samsung/StringCal.java
>  public final class StringCal {
이유를 정확하게 알고계시네요.😀 사실 별거 없어요, 상속을 못하게 하려고 쓰는 거지. 

제가 쓰는 이유는 다른 개발자가 실수로 사용 못하게 방지하는 효과도 있고, 상속할 때 한번 더 생각해보게 되더라구요.
코틀린처럼 `final`이 기본이 되고,  `open` 같이 상속을 열어주는  키워드가 있는게 자연스러운게 아닐까하는 생각도..?

다만 `그냥 이유는 없고 써보고 싶어서` 는 개발자가 들으면 입에 거품무는 멘트(?) 라서
`상속을 할 필요가 없는 객체라서, 의존성을 최소화하려고 final을 넣었습니다` 처럼 힙-하게 말씀하시는게 나을 거 같아요 ㅋㅋ

2022-04-29 13:00 UTC, JiwonDev commented on src/main/java/com/samsung/StringCal.java
> +    public String[] split (String str) {
지금은 큰 상관없겠지만, 다른 개발자와 협업하는 코드에 저런 식의 주석은 상당히 안좋은 습관인 거 같아요.😀
사용하지 않는 코드나 주석은 제거해주세요.

만약 이것저것 시도했던 흔적을 남기고 싶다면, 이는 주석말고 Git의 브렌치를 새로 파시거나 Stash/UnStash 기능을 사용해보시는걸 추천드립니다. 훨씬 깔끔하고 실험용 코드도 버전별로 관리할 수 있으니까요.

2022-04-29 13:01 UTC, JiwonDev commented on src/main/java/com/samsung/StringCal.java
> +                formula.add((splitArr[i]));
해당 부분을 메서드로 추상화해서, 다른 개발자가 읽었을 때 이해하기 쉽도록 바꿀 수 있지 않을까요?

`try에서는 숫자를, catch에서는 연산자를 formula list에 추가` 를 왜하는지 이해하기 어렵지만
```java
formula.add(num);
num = "";
exceptionCnt++;
formula.add((splitArr[i]));
 ```
 
`연산자를 추가한다` 라는 말은 직관적으로 이해할 수 있으니까요.
```java
addOperator(...)
```

2022-04-29 13:02 UTC, JiwonDev commented on src/main/java/com/samsung/StringCal.java
> +    public List<String> makeFormula (String[] splitArr) {
개인적으로 `private`를 습관처럼 기본으로 사용하시고, 꼭 필요할 때 `public`으로 바꾸는 걸 추천드려요.

`private`는 수정하기 쉽지만, `public`은 외부에서 사용해버리면 수정하기 어려워지니까요.

2022-05-01 13:21 UTC, Eco-Min approved these changes

2022-05-01 13:22 UTC, Eco-Min requested changes
좋았엉요

2022-05-02 01:03 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
>  public final class StringCal {
힙-하게!

2022-05-02 01:08 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +        String[] splitArr = strFormula.split("");
그부분에서는 무조건 하나씩 끊어주기만 하고,
10의자리 숫자(또는 그이상의 숫자)와 연산자로 나눠서 담는 건 try catch 부분에서 처리됩니다~

2022-05-02 01:33 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +        String[] splitArr = strFormula.split("");
if문이 아닌 `try-catch` 로 처리한 이유는 
한글자씩 끊어서 넣어준 숫자와 연산자들을 int형으로 파싱하는데 
연산자부분에서 오류가 생기기 때문에 사용했고
그 오류를 사용해서 숫자와 연산자를 나눠서 담았습니다

2022-05-02 01:35 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +        String[] splitArr = strFormula.split("");
지금 방식보다
`splitFormula()` 에서 파싱 및 10의자리 처리까지 같이 해주고
`try-catch`부분의 숫자, 연산자 나눠서 담는 처리를 `if`문으로 하는게 더 좋을것같기도해요

2022-05-02 01:50 UTC, somyiha commented on src/main/java/com/samsung/StringCal.java
> +    public List<String> makeFormula (String[] splitArr) {
`private`를 습관처럼!

2022-05-02 02:01 UTC, Eco-Min commented on src/main/java/com/samsung/StringCal.java
> +                formula.remove(i);
그러면 큐랑 비슷해 보이는데 어떤점이 더 좋아서 사용하게 되었나요?

2022-05-02 05:13 UTC, JiwonDev commented on src/main/java/com/samsung/StringCal.java
> +        String[] splitArr = strFormula.split("");
음.. 지금 PR에서는 그대로 사용해도 괜찮지만
try-catch를 정상로직에 사용하는 건 고민해볼 필요가 있긴합니다.

📌 JVM 예외처리는 생각보다 비용이 큽니다.
- 예외 객체를 생성하고, 매번 메서드 호출순서(스택트레이스)를 수집해야합니다.
- 모니터링, 디버깅할 때 발생한 예외를 추적합니다.


📌 다만 이 문제들은 `런타임 예외`에만 해당됩니다. 그럼 비용에 큰 문제가 없는 `컴파일 타임 예외`는 괜찮을까요?
아뇨, 비용을 제외하더라도 정상로직에 try-catch사용은 좋지 않습니다.
- 다른 개발자가 읽었을 때, 이 부분이 정상 로직임을 알아내기 어렵습니다. Exception은 예외상황이라고 생각하니까요.
- 예외가 중첩되면 유지보수가 불가능해집니다. 다른 예외를 삼켜`catch`버리기 쉽습니다.
- 가독성도 나쁩니다. `if-else`보다 `try-catch`가 훨씬 읽기 힘듭니다.


📌 내 코드뿐만 아니라, 프로젝트 전체에 영향을 끼치기도 합니다.
- throw 때문에 코드가 순서대로 실행되지 않게 됩니다. `C언어의 goto`
- 정상로직임에도 실수로 예외를 놓치게되면 프로그램이 멈춰 다른 코드에 큰 영향을 끼치게 됩니다.
- 정상로직에서 발생한 예외는 디버깅 & 모니터링을 매우 어렵게 만듭니다.

심심하면 [try-catch를 논리연산으로 쓰면 안되나요?](https://softwareengineering.stackexchange.com/questions/107723/arguments-for-or-against-using-try-catch-as-logical-operators) 를 읽어보셔도 좋을 거같아요.

2022-05-02 08:49 UTC, JiwonDev approved these changes
LGTM 남은 답변들 resolve 해주시고, 바로 머지해주시면 됩니다 :)

2022-05-02 13:12 UTC, Eco-Min approved these changes

2022-05-02 13:13 UTC, merged